version: "3"
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150"
      - "4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171"
  api-gateway:
    image: export-api-gateway:latest
    depends_on:
      - nsqlookupd
    ports:
      - "8080:8080"
  export-port-database:
    image: export-port-database:latest
  export-port-scanner:
    image: export-port-scanner:latest
